[tool.black]
line-length = 120
target-version = ['py37']

[tool.flake8]
exclude = "wandb,__init__.py"
max-line-length = 120
ignore = "E501,W503"
# E501: Line too long
# W503: Line break occurred before binary operator

[tool.isort]
line_length = 120
